import { SingleBar, Presets } from 'cli-progress';
import db from './index';
import {
    regions,
    states,
    counties,
    countyRegions,
    channelSubscriptions,
    filteredSpecies,
} from './schema';

const countyRegionMapping = {
    Butte: 'US-CA-SC',
    Colusa: 'US-CA-SC',
    'El Dorado': 'US-CA-SC',
    Glenn: 'US-CA-SC',
    Lassen: 'US-CA-SC',
    Modoc: 'US-CA-SC',
    Nevada: 'US-CA-SC',
    Placer: 'US-CA-SC',
    Plumas: 'US-CA-SC',
    Sacramento: 'US-CA-SC',
    Shasta: 'US-CA-SC',
    Sierra: 'US-CA-SC',
    Siskiyou: 'US-CA-SC',
    Sutter: 'US-CA-SC',
    Tehama: 'US-CA-SC',
    Yolo: 'US-CA-SC',
    Yuba: 'US-CA-SC',
    'Del Norte': 'US-CA-NC',
    Humboldt: 'US-CA-NC',
    Lake: 'US-CA-NC',
    Mendocino: 'US-CA-NC',
    Napa: 'US-CA-SFB',
    Sonoma: 'US-CA-SFB',
    Trinity: 'US-CA-NC',
    Alameda: 'US-CA-SFB',
    'Contra Costa': 'US-CA-SFB',
    Marin: 'US-CA-SFB',
    'San Francisco': 'US-CA-SFB',
    'San Mateo': 'US-CA-SFB',
    'Santa Clara': 'US-CA-SFB',
    Solano: 'US-CA-SFB',
    Alpine: 'US-CA-NSJV',
    Amador: 'US-CA-NSJV',
    Calaveras: 'US-CA-NSJV',
    Madera: 'US-CA-NSJV',
    Mariposa: 'US-CA-NSJV',
    Merced: 'US-CA-NSJV',
    Mono: 'US-CA-NSJV',
    'San Joaquin': 'US-CA-NSJV',
    Stanislaus: 'US-CA-NSJV',
    Tuolumne: 'US-CA-NSJV',
    Monterey: 'US-CA-CC',
    'San Benito': 'US-CA-CC',
    'San Luis Obispo': 'US-CA-CC',
    'Santa Barbara': 'US-CA-CC',
    Ventura: 'US-CA-CC',
    'Santa Cruz': 'US-CA-CC',
    Fresno: 'US-CA-SSJV',
    Inyo: 'US-CA-SSJV',
    Kern: 'US-CA-SSJV',
    Kings: 'US-CA-SSJV',
    Tulare: 'US-CA-SSJV',
    'Los Angeles': 'US-CA-LA',
    'San Bernardino': 'US-CA-IE',
    Riverside: 'US-CA-IE',
    Orange: 'US-CA-OR',
    'San Diego': 'US-CA-SDI',
    Imperial: 'US-CA-SDI',
};

const regionChannels = {
    'US-CA-SDI': ['1156452037337301003'],
    'US-CA-OR': ['1156452064625426452'],
    'US-CA-LA': ['1156452053145616394'],
    'US-CA-IE': ['1156452787492757547'],
    'US-CA-SFB': ['1156452216631197817'],
    'US-CA-CC': ['1156452330590445649'],
    'US-CA-NSJV': ['1156452103133343814'],
    'US-CA-SSJV': ['1156452147156758589'],
    'US-CA-SC': ['1156452191129841674'],
    'US-CA-NC': ['1156452314236862484'],
};

const californiaFilter = [
    'Emu',
    'Bar-headed Goose',
    'Snow Goose',
    "Ross's Goose",
    "Snow x Ross's Goose (hybrid)",
    'Graylag Goose',
    'Swan Goose',
    'Graylag x Swan Goose (hybrid)',
    'Greater White-fronted Goose',
    'Emperor x Greater White-fronted Goose (hybrid)',
    'Snow x Greater White-fronted Goose (hybrid)',
    'Brant',
    'Brant (Black)',
    'Barnacle Goose',
    'Cackling Goose',
    'Cackling Goose (minima)',
    'Cackling Goose (Aleutian)',
    'Greater White-fronted x Cackling Goose (hybrid)',
    'Canada Goose',
    'Canada Goose (moffitti/maxima)',
    'Canada Goose (canadensis Group)',
    'Canada Goose (occidentalis/fulva)',
    'Swan Goose x Canada Goose (hybrid)',
    'Greater White-fronted x Canada Goose (hybrid)',
    'Graylag x Canada Goose (hybrid)',
    'Domestic goose sp. x Canada Goose (hybrid)',
    'Snow x Canada Goose (hybrid)',
    'Barnacle x Canada Goose (hybrid)',
    'Hawaiian Goose',
    'Red-breasted Goose',
    'Mute Swan',
    'Black Swan',
    'Black-necked Swan',
    'Trumpeter Swan',
    "Tundra Swan (Bewick's)",
    'Tundra Swan (Whistling)',
    'Tundra Swan',
    'Upland Goose',
    'Egyptian Goose',
    'Ruddy Shelduck',
    'South African Shelduck',
    'Common Shelduck',
    'Crested Duck',
    'Muscovy Duck',
    'Ringed Teal',
    'Wood Duck',
    'Mandarin Duck',
    'Blue-winged Teal',
    'Cinnamon Teal',
    'Blue-winged x Cinnamon Teal (hybrid)',
    'Northern Shoveler',
    'Blue-winged Teal x Northern Shoveler (hybrid)',
    'Cinnamon Teal x Northern Shoveler (hybrid)',
    'Gadwall',
    'Northern Shoveler x Gadwall (hybrid)',
    'Eurasian Wigeon',
    'American Wigeon',
    'Northern Shoveler x American Wigeon (hybrid)',
    'Gadwall x American Wigeon (hybrid)',
    'Eurasian x American Wigeon (hybrid)',
    'Chiloe Wigeon',
    'Mallard',
    'Muscovy Duck x Mallard (hybrid)',
    'Wood Duck x Mallard (hybrid)',
    'Northern Shoveler x Mallard (hybrid)',
    'Gadwall x Mallard (hybrid)',
    'American Wigeon x Mallard (hybrid)',
    'Mallard x Mexican Duck (hybrid)',
    'White-cheeked Pintail',
    'Northern Pintail',
    'Gadwall x Northern Pintail (hybrid)',
    'American Wigeon x Northern Pintail (hybrid)',
    'Mallard x Northern Pintail (hybrid)',
    'Green-winged Teal',
    'Green-winged Teal (Eurasian)',
    'Green-winged Teal (American)',
    'Baikal x Green-winged Teal (hybrid)',
    'Garganey x Green-winged Teal (hybrid)',
    'Blue-winged x Green-winged Teal (hybrid)',
    'Cinnamon x Green-winged Teal (hybrid)',
    'Gadwall x Green-winged Teal (hybrid)',
    'Eurasian Wigeon x Green-winged Teal (hybrid)',
    'American Wigeon x Green-winged Teal (hybrid)',
    'Mallard Wigeon x Green-winged Teal (hybrid)',
    'Northern Pintail x Green-winged Teal (hybrid)',
    'Red-crested Pochard',
    'Canvasback',
    'Redhead',
    'Canvasback x Redhead (hybrid)',
    'Ring-necked Duck',
    'Redhead x Ring-necked Duck (hybrid)',
    'Tufted Duck',
    'Ring-necked x Tufted Duck (hybrid)',
    'Greater Scaup',
    'Ring-necked Duck x Greater Scaup (hybrid)',
    'Tufted Duck x Greater Scaup (hybrid)',
    'Lesser Scaup',
    'Ring-necked Duck x Lesser Scaup (hybrid)',
    'Tufted Duck x Lesser Scaup (hybrid)',
    'Ring-necked Duck x scaup sp. (hybrid)',
    'Tufted Duck x scaup sp. (hybrid)',
    'Harlequin Duck',
    'Surf Scoter',
    'White-winged Scoter',
    'Black Scoter',
    'Long-tailed Duck',
    'Bufflehead',
    'Common Goldeneye',
    'Bufflehead x Common Goldeneye (hybrid)',
    "Barrow's Goldeneye",
    "Common x Barrow's Goldeneye (hybrid)",
    'Hooded Merganser',
    'Bufflehead x Hooded Merganser (hybrid)',
    'Common Goldeneye x Hooded Merganser (hybrid)',
    "Barrow's Goldeneye x Hooded Merganser (hybrid)",
    'goldeneye sp. x Hooded Merganser (hybrid)',
    'Common Merganser',
    'Common Merganser (North American)',
    'Red-breasted Merganser',
    'Ruddy Duck',
    'Helmeted Guineafowl',
    'Mountain Quail',
    'Northern Bobwhite',
    'Scaled Quail',
    'California Quail',
    "Gambel's Quail",
    "California x Gambel's Quail (hybrid)",
    'Wild Turkey',
    'Ruffed Grouse',
    'Greater Sage-Grouse',
    'Sooty Grouse',
    'Sharp-tailed Grouse',
    'White-tailed Ptarmigan',
    'Gray Partridge',
    "Reeves's Pheasant",
    'Golden Pheasant',
    "Lady Amherst's Pheasant",
    "Golden x Lady Amherst's Pheasant (hybrid)",
    'Ring-necked Pheasant',
    'Kalij Pheasant',
    'Silver Pheasant',
    'Indian Peafowl',
    'Gray Peacock-Pheasant',
    'Red Junglefowl',
    'Black Francolin',
    'Common Quail',
    'Japanese Quail',
    'Chukar',
    'Chilean Flamingo',
    'American Flamingo',
    'Greater Flamingo',
    'Lesser Flamingo',
    'Pied-billed Grebe',
    'Horned Grebe',
    'Red-necked Grebe',
    'Eared Grebe',
    'Western Grebe',
    "Clark's Grebe",
    "Western x Clark's Grebe (hybrid)",
    'Rock Pigeon',
    'Rock Pigeon (Feral Pigeon)',
    'Speckled Pigeon',
    'Band-tailed Pigeon',
    'Band-tailed Pigeon (Northern)',
    'Eurasian Collared-Dove',
    'African Collared-Dove',
    'Eurasian x African Collared-Dove (hybrid)',
    'Spotted Dove',
    'Laughing Dove',
    'Namaqua Dove',
    'Diamond Dove',
    'Zebra Dove',
    'Inca Dove',
    'Common Ground Dove',
    'Ruddy Ground Dove',
    'White-winged Dove',
    'Mourning Dove',
    'White-cheeked Turaco',
    'Greater Roadrunner',
    'Yellow-billed Cuckoo',
    'Lesser Nighthawk',
    'Common Nighthawk',
    'Common Poorwill',
    'Mexican Whip-poor-will',
    'Black Swift',
    'Black Swift (borealis)',
    'Chimney Swift',
    "Vaux's Swift",
    'White-throated Swift',
    'Black-chinned Hummingbird',
    "Anna's Hummingbird",
    "Black-chinned x Anna's Hummingbird (hybrid)",
    "Costa's Hummingbird",
    "Black-chinned x Costa's Hummingbird (hybrid)",
    "Anna's x Costa's Hummingbird (hybrid)",
    'Calliope Hummingbird',
    'Black-chinned x Calliope Hummingbird (hybrid)',
    "Anna's x Calliope Hummingbird (hybrid)",
    'Rufous Hummingbird',
    'Black-chinned x Rufous Hummingbird (hybrid)',
    "Anna's x Rufous Hummingbird (hybrid)",
    'Calliope x Rufous Hummingbird (hybrid)',
    "Allen's Hummingbird",
    "Anna's x Allen's Hummingbird (hybrid)",
    "Rufous x Allen's Hummingbird (hybrid)",
    'Broad-tailed Hummingbird',
    "Anna's Hummingbird x Selasphorus sp. (hybrid)",
    'Broad-billed Hummingbird',
    "Ridgway's Rail",
    "Ridgway's Rail (Light-footed)",
    'Virginia Rail',
    'Sora',
    'Common Gallinule',
    'American Coot',
    'American Coot (Red-shielded)',
    'American Coot (White-shielded)',
    'Common Gallinule x American Coot (hybrid)',
    'Yellow Rail',
    'Black Rail',
    'Gray Crowned-Crane',
    'Demoiselle Crane',
    'Sandhill Crane',
    'Sandhill Crane (canadensis)',
    'Black-necked Stilt',
    'Black-necked Stilt (Black-necked)',
    'American Avocet',
    'American Oystercatcher',
    'Black Oystercatcher',
    'American x Black Oystercatcher (hybrid)',
    'Black-bellied Plover',
    'American Golden-Plover',
    'Pacific Golden-Plover',
    'Spur-winged Lapwing',
    'Snowy Plover',
    'Semipalmated Plover',
    'Killdeer',
    'Mountain Plover',
    'Upland Sandpiper',
    'Whimbrel',
    'Whimbrel (Hudsonian)',
    'Long-billed Curlew',
    'Bar-tailed Godwit',
    'Bar-tailed Godwit (Siberian)',
    'Hudsonian Godwit',
    'Marbled Godwit',
    'Ruddy Turnstone',
    'Black Turnstone',
    'Red Knot',
    'Surfbird',
    'Great Knot x Surfbird (hybrid)',
    'Ruff',
    'Sharp-tailed Sandpiper',
    'Stilt Sandpiper',
    'Curlew Sandpiper',
    'Long-toed Stint',
    'Sanderling',
    'Dunlin',
    'Rock Sandpiper',
    "Baird's Sandpiper",
    'Least Sandpiper',
    'Buff-breasted Sandpiper',
    'Pectoral Sandpiper',
    'Semipalmated Sandpiper',
    'Western Sandpiper',
    'Short-billed Dowitcher',
    'Long-billed Dowitcher',
    "Wilson's Snipe",
    "Wilson's Phalarope",
    'Red-necked Phalarope',
    'Red Phalarope',
    'Spotted Sandpiper',
    'Solitary Sandpiper',
    'Wandering Tattler',
    'Greater Yellowlegs',
    'Willet',
    'Lesser Yellowlegs',
    'South Polar Skua',
    'Pomarine Jaeger',
    'Parasitic Jaeger',
    'Long-tailed Jaeger',
    'Common Murre',
    'Pigeon Guillemot',
    'Marbled Murrelet',
    "Scripps's Murrelet",
    'Guadalupe Murrelet',
    "Craveri's Murrelet",
    'Ancient Murrelet',
    "Cassin's Auklet",
    'Parakeet Auklet',
    'Rhinoceros Auklet',
    'Horned Puffin',
    'Tufted Puffin',
    'Black-legged Kittiwake',
    "Sabine's Gull",
    "Bonaparte's Gull",
    'Little Gull',
    'Laughing Gull',
    "Franklin's Gull",
    "Heermann's Gull",
    'Short-billed Gull',
    'Ring-billed Gull',
    'Western Gull',
    'Yellow-footed Gull',
    'California Gull',
    'California Gull (californicus)',
    'California Gull (albertaensis)',
    'Herring Gull',
    'Herring Gull (American)',
    'Iceland Gull',
    "Iceland Gull (Thayer's)",
    'Lesser Black-backed Gull',
    'Slaty-backed Gull',
    'Glaucous-winged Gull',
    'Western x Glaucous-winged Gull (hybrid)',
    'Herring x Glaucous-winged Gull (hybrid)',
    'Slaty-backed x Glaucous-winged Gull (hybrid)',
    'Glaucous x Glaucous-winged Gull (hybrid)',
    'Glaucous Gull',
    'Herring x Glaucous Gull (hybrid)',
    'Glaucous-winged x Glaucous Gull (hybrid)',
    'Least Tern',
    'Gull-billed Tern',
    'Caspian Tern',
    'Black Tern',
    'Common Tern',
    'Arctic Tern',
    "Forster's Tern",
    'Royal Tern',
    'Elegant Tern',
    'Sandwich x Elegant Tern (hybrid)',
    'Black Skimmer',
    'Red-billed Tropicbird',
    'Red-throated Loon',
    'Pacific Loon',
    'Common Loon',
    'Yellow-billed Loon',
    'Laysan Albatross',
    'Black-footed Albatross',
    'Laysan x Black-footed Albatross (hybrid)',
    "Wilson's Storm-Petrel",
    'Fork-tailed Storm-Petrel',
    "Leach's Storm-Petrel",
    "Townsend's Storm-Petrel",
    'Ashy Storm-Petrel',
    'Black Storm-Petrel',
    "Tristram's Storm-Petrel",
    'Least Storm-Petrel',
    'Northern Fulmar',
    "Murphy's Petrel",
    'Mottled Petrel',
    'Hawaiian Petrel',
    "Cook's Petrel",
    'Pink-footed Shearwater',
    'Flesh-footed Shearwater',
    "Buller's Shearwater",
    'Sooty Shearwater',
    'Short-tailed Shearwater',
    'Manx Shearwater',
    'Black-vented Shearwater',
    'Magnificent Frigatebird',
    'Masked Booby',
    'Nazca Booby',
    'Blue-footed Booby',
    'Brown Booby',
    "Brown Booby (Brewster's)",
    'Blue-footed x Brown Booby (hybrid)',
    'Red-footed Booby',
    'African Darter',
    "Brandt's Cormorant",
    'Pelagic Cormorant',
    'Double-crested Cormorant',
    'Neotropic Cormorant',
    'Double-crested x Neotropic Cormorant (hybrid)',
    'American White Pelican',
    'Brown Pelican',
    'Brown Pelican (California)',
    'Pink-backed Pelican',
    'American Bittern',
    'Least Bittern',
    'Great Blue Heron',
    'Great Egret',
    'Great Egret (American)',
    'Snowy Egret',
    'Little Blue Heron',
    'Snowy Egret x Little Blue Heron (hybrid)',
    'Tricolored Heron',
    'Reddish Egret',
    'Cattle Egret',
    'Western Cattle Egret',
    'Green Heron',
    'Black-crowned Night Heron',
    'Yellow-crowned Night Heron',
    'Yellow-crowned Night Heron (Yellow-crowned)',
    'Black crowned x Yellow-crowned Night Heron (hybrid)',
    'White-faced Ibis',
    'Glossy x White-faced Ibis (hybrid)',
    'African Sacred Ibis',
    'Roseate Spoonbill',
    'California Condor',
    'Turkey Vulture',
    'Turkey Vulture (Northern)',
    'Osprey',
    'White-tailed Kite',
    'Golden Eagle',
    'Northern Harrier',
    'Sharp-shinned Hawk',
    "Cooper's Hawk",
    'American Goshawk',
    'Bald Eagle',
    'Savanna Hawk',
    "Harris's Hawk",
    'Red-shouldered Hawk',
    'Red-shouldered Hawk (elegans)',
    'Common Black x Red-shouldered Hawk (hybrid)',
    'Broad-winged Hawk',
    "Swainson's Hawk",
    'Zone-tailed Hawk',
    'Red-tailed Hawk',
    'Rough-legged Hawk',
    'Red-tailed x Rough-legged Hawk (hybrid)',
    'Ferruginous Hawk',
    'Barn Owl',
    'Flammulated Owl',
    'Western Screech-Owl',
    'Great Horned Owl',
    'Northern Pygmy-Owl',
    'Burrowing Owl',
    'Spotted Owl',
    'Barred Owl',
    'Spotted x Barred Owl (hybrid)',
    'Great Gray Owl',
    'Long-eared Owl',
    'Short-eared Owl',
    'Northern Saw-whet Owl',
    'Oriental Pied-Hornbill',
    'Belted Kingfisher',
    'Lilac-breasted Roller',
    'Keel-billed Toucan',
    "Williamson's Sapsucker",
    'Yellow-bellied Sapsucker',
    'Red-naped Sapsucker',
    'Yellow-bellied x Red-naped Sapsucker (hybrid)',
    'Red-breasted Sapsucker',
    'Red-breasted Sapsucker (daggetti)',
    'Yellow-bellied x Red-breasted Sapsucker (hybrid)',
    'Red-naped x Red-breasted Sapsucker (hybrid)',
    "Lewis's Woodpecker",
    'Acorn Woodpecker',
    'Acorn Woodpecker (Acorn)',
    'Gila Woodpecker',
    'Black-backed Woodpecker',
    'Downy Woodpecker',
    'Downy Woodpecker (Pacific)',
    "Nuttall's Woodpecker",
    "Downy x Nuttall's Woodpecker (hybrid)",
    'Ladder-backed Woodpecker',
    "Nuttall's x Ladder-backed Woodpecker (hybrid)",
    'Hairy Woodpecker',
    'Hairy Woodpecker (Pacific)',
    'Downy x Hairy Woodpecker (hybrid)',
    "Nuttall's x Hairy Woodpecker (hybrid)",
    'Ladder-backed x Hairy Woodpecker (hybrid)',
    'White-headed Woodpecker',
    'Pileated Woodpecker',
    'Northern Flicker',
    'Northern Flicker (Red-shafted)',
    'Northern Flicker (Yellow-shafted)',
    'Northern Flicker (Yellow-shafted x Red-shafted)',
    'Gilded Flicker',
    'Northern x Gilded Flicker (hybrid)',
    'Yellow-headed Caracara',
    'American Kestrel',
    'Merlin',
    'Merlin (Black)',
    'Merlin (Prairie)',
    'Peregrine Falcon',
    'Peregrine Falcon (Tundra)',
    'Peregrine Falcon (North American)',
    'Prairie Falcon',
    'Peregrine x Prairie Falcon (hybrid)',
    'Sulphur-crested Cockatoo',
    'Cockatiel',
    'Eclectus Parrot',
    'Alexandrine Parakeet',
    'Rose-ringed Parakeet',
    'Crimson Rosella',
    'Red-rumped Parrot',
    'Budgerigar',
    'Rainbow Lorikeet',
    'Rosy-faced Lovebird',
    "Fischer's Lovebird",
    'Yellow-collared Lovebird',
    "Fischer's x Yellow-collared Lovebird (hybrid)",
    'Gray Parrot',
    "Meyer's Parrot",
    'Monk Parakeet',
    'White-winged Parakeet',
    'Yellow-chevroned Parakeet',
    'Scaly-headed Parrot',
    'Red-crowned Parrot',
    'Lilac-crowned Parrot',
    'Red-crowned x Lilac-crowned Parrot (hybrid)',
    'Red-lored Parrot',
    'Red-crowned x Red-lored Parrot (hybrid)',
    'Yellow-headed Parrot',
    'Yellow-crowned Parrot',
    'Turquoise-fronted Parrot',
    'White-fronted Parrot',
    'Mealy Parrot',
    'Orange-winged Parrot',
    'Pacific Parrotlet',
    'Yellow-faced Parrotlet',
    'Maroon-bellied Parakeet',
    'Black-capped Parakeet',
    'Burrowing Parakeet',
    'Hyacinth Macaw',
    'Orange-fronted Parakeet',
    'Nanday Parakeet',
    'Sun Parakeet',
    'Jandaya Parakeet',
    'Blue-and-yellow Macaw',
    'Military Macaw',
    'Scarlet Macaw',
    'Red-and-green Macaw',
    'Blue-crowned Parakeet',
    'Green Parakeet',
    'Mitred Parakeet',
    'Red-masked Parakeet',
    'White-eyed Parakeet',
    'Olive-sided Flycatcher',
    'Western Wood-Pewee',
    'Willow Flycatcher',
    'Least Flycatcher',
    "Hammond's Flycatcher",
    'Gray Flycatcher',
    'Dusky Flycatcher',
    'Western Flycatcher',
    'Western Flycatcher (Pacific-slope)',
    'Western Flycatcher (Cordilleran)',
    'Western Flycatcher (Pacific-slope x Cordilleran Flycatcher)',
    'Black Phoebe',
    'Black Phoebe (Northern)',
    'Eastern Phoebe',
    "Say's Phoebe",
    "Black x Say's Phoebe (hybrid)",
    'Vermilion Flycatcher',
    'Vermilion Flycatcher (Northern)',
    'Dusky-capped Flycatcher',
    'Ash-throated Flycatcher',
    'Great Crested Flycatcher',
    'Brown-crested Flycatcher',
    'Sulphur-bellied Flycatcher',
    'Tropical Kingbird',
    "Cassin's Kingbird",
    'Western Kingbird',
    'Eastern Kingbird',
    'Scissor-tailed Flycatcher',
    'Western Kingbird x Scissor-tailed Flycatcher (hybrid)',
    'White-eyed Vireo',
    "Bell's Vireo",
    "Bell's Vireo (Least)",
    "Bell's Vireo (Eastern)",
    'Gray Vireo',
    "Hutton's Vireo",
    "Hutton's Vireo (Pacific)",
    'Yellow-throated Vireo',
    "Cassin's Vireo",
    'Blue-headed Vireo',
    'Plumbeous Vireo',
    'Plumbeous Vireo (Plumbeous)',
    'Philadelphia Vireo',
    'Warbling Vireo',
    'Warbling Vireo (Western)',
    'Red-eyed Vireo',
    'Philadelphia x Red-eyed Vireo (hybrid)',
    'Yellow-green Vireo',
    'Loggerhead Shrike',
    'Northern Shrike',
    'Canada Jay',
    'Black-throated Magpie-Jay',
    'White-throated Magpie-Jay',
    'Green Jay',
    'Pinyon Jay',
    "Steller's Jay",
    "Steller's Jay (Coastal)",
    'Island Scrub-Jay',
    'California Scrub-Jay',
    "Woodhouse's Scrub-Jay",
    'Eurasian Magpie',
    'Black-billed Magpie',
    'Yellow-billed Magpie',
    "Clark's Nutcracker",
    'House Crow',
    'American Crow',
    'Pied Crow',
    'Common Raven',
    'Black-capped Chickadee',
    'Mountain Chickadee',
    'Chestnut-backed Chickadee',
    'Eurasian Blue Tit',
    'Oak Titmouse',
    'Juniper Titmouse',
    'Great Tit',
    'Japanese Tit',
    'Verdin',
    'Horned Lark',
    'Northern Rough-winged Swallow',
    'Purple Martin',
    'Tree Swallow',
    'Violet-green Swallow',
    'Bank Swallow',
    'Barn Swallow',
    'Tree x Barn Swallow (hybrid)',
    'Cliff Swallow',
    'Barn x Cliff Swallow (hybrid)',
    'Red-vented Bulbul',
    'Red-whiskered Bulbul',
    'Red-vented x Red-whiskered Bulbul (hybrid)',
    'White-eared Bulbul',
    'Wood Warbler',
    'Bushtit',
    'Wrentit',
    'Vinous-throated Parrotbill',
    "Swinhoe's White-eye",
    'Warbling White-eye',
    'Indian White-eye',
    'Red-billed Leiothrix',
    'Ruby-crowned Kinglet',
    'Golden-crowned Kinglet',
    'Red-breasted Nuthatch',
    'White-breasted Nuthatch',
    'White-breasted Nuthatch (Pacific)',
    'Pygmy Nuthatch',
    'Brown Creeper',
    'Brown Creeper (occidentalis Group)',
    'Blue-gray Gnatcatcher',
    'Blue-gray Gnatcatcher (obscura Group)',
    'Black-tailed Gnatcatcher',
    'California Gnatcatcher',
    'Rock Wren',
    'Rock Wren (Northern)',
    'Canyon Wren',
    'House Wren',
    'House Wren (Northern)',
    'Pacific Wren',
    'Marsh Wren',
    'Marsh Wren (paludicola Group)',
    "Bewick's Wren",
    "Bewick's Wren (spilurus Group)",
    "Bewick's Wren (mexicanus Group)",
    'Cactus Wren',
    'American Dipper',
    'Common Hill Myna',
    'European Starling',
    'Bali Myna',
    'Brahminy Starling',
    'Common Myna',
    'Crested Myna',
    'Purple Starling',
    'Blue Mockingbird',
    'Gray Catbird',
    'Brown Thrasher',
    "Bendire's Thrasher",
    'California Thrasher',
    "LeConte's Thrasher",
    'Crissal Thrasher',
    'California x Crissal Thrasher (hybrid)',
    'Sage Thrasher',
    'Northern Mockingbird',
    'Western Bluebird',
    'Mountain Bluebird',
    'Western x Mountain Bluebird (hybrid)',
    "Townsend's Solitaire",
    'Varied Thrush',
    "Swainson's Thrush",
    "Swainson's Thrush (Russet-backed)",
    "Swainson's Thrush (Olive-backed)",
    'Hermit Thrush',
    'Hermit Thrush (guttatus Group)',
    'American Robin',
    'American Robin (migratorius Group)',
    'Bohemian Waxwing',
    'Cedar Waxwing',
    'Gray Silky-flycatcher',
    'Phainopepla',
    'Golden-fronted Leafbird',
    'Golden Palm Weaver',
    'Taveta Golden-Weaver',
    'Southern Masked-Weaver',
    'Village Weaver',
    'Black-headed Weaver',
    'Northern Red Bishop',
    'Zanzibar Red Bishop',
    'Black-winged Bishop',
    'Yellow-crowned Bishop',
    'White-winged Widowbird',
    'Diamond Firetail',
    'Red-browed Firetail',
    'Double-barred Finch',
    'Zebra Finch',
    'Bronze Mannikin',
    'Indian Silverbill',
    'Scaly-breasted Munia',
    'Scaly-breasted Munia (Checkered)',
    'White-rumped Munia',
    'Tricolored Munia',
    'Chestnut Munia',
    'White-headed Munia',
    'Gouldian Finch',
    'Orange-cheeked Waxbill',
    'Common Waxbill',
    'Black-rumped Waxbill',
    'Crimson-rumped Waxbill',
    'Cut-throat',
    'Zebra Waxbill',
    'Red Avadavat',
    'Red-cheeked Cordonbleu',
    'Blue-capped Cordonbleu',
    'Green-winged Pytilia',
    "Peters's Twinspot",
    'Red-billed Firefinch',
    'African Firefinch',
    'Pin-tailed Whydah',
    'Togo Paradise-Whydah',
    'Broad-tailed Paradise-Whydah',
    'Village Indigobird',
    'House Sparrow',
    'Eurasian Tree Sparrow',
    'Sudan Golden Sparrow',
    'White Wagtail',
    'White Wagtail (Black-backed)',
    'White Wagtail (Pied)',
    'Red-throated Pipit',
    'American Pipit',
    "Sprague's Pipit",
    'Evening Grosbeak',
    'Evening Grosbeak (type 1)',
    'Pine Grosbeak',
    'Gray-crowned Rosy-Finch',
    'House Finch',
    'House Finch (Common)',
    'Purple Finch',
    'Purple Finch (Western)',
    "Cassin's Finch",
    'European Greenfinch',
    'White-rumped Seedeater',
    'Yellow-fronted Canary',
    'Black-throated Canary',
    'Streaky Seedeater',
    'Common Redpoll',
    'Red Crossbill',
    'Red Crossbill (Ponderosa Pine or type 2)',
    'Red Crossbill (Western Hemlock or type 3)',
    'Red Crossbill (Douglas-fir or type 4)',
    'Red Crossbill (Lodgepole Pine or type 5)',
    'Red Crossbill (Sitka Spruce or type 10)',
    'European Goldfinch',
    'European Serin',
    'Island Canary',
    'Pine Siskin',
    'Lesser Goldfinch',
    "Lawrence's Goldfinch",
    'American Goldfinch',
    'Black Siskin',
    'Lapland Longspur',
    'Chestnut-collared Longspur',
    'Thick-billed Longspur',
    'Snow Bunting',
    "Cassin's Sparrow",
    'Grasshopper Sparrow',
    'Chipping Sparrow',
    'Clay-colored Sparrow',
    'Black-chinned Sparrow',
    "Brewer's Sparrow",
    "Clay-colored x Brewer's Sparrow (hybrid)",
    'Black-throated Sparrow',
    'Lark Sparrow',
    'Lark Bunting',
    'American Tree Sparrow',
    'Fox Sparrow',
    'Fox Sparrow (Sooty)',
    'Fox Sparrow (Thick-billed)',
    'Dark-eyed Junco',
    'Dark-eyed Junco (Pink-sided)',
    'Dark-eyed Junco (Oregon)',
    'Dark-eyed Junco (Slate-colored)',
    'Dark-eyed Junco (Slate-colored/cismontanus)',
    'Dark-eyed Junco (cismontanus)',
    'Dark-eyed Junco (Gray-headed)',
    'White-crowned Sparrow',
    'White-crowned Sparrow (oriantha)',
    "White-crowned Sparrow (Gambel's)",
    'White-crowned Sparrow (Dark-lored)',
    'White-crowned Sparrow (Yellow-billed)',
    'Dark-eyed Junco x White-crowned Sparrow (hybrid)',
    'Golden-crowned Sparrow',
    'White-crowned Sparrow (pugetensis)',
    'White-crowned x Golden-crowned Sparrow (hybrid)',
    "Harris's Sparrow",
    'White-throated Sparrow',
    'White-crowned x White-throated Sparrow (hybrid)',
    'Golden-crowned x White-throated Sparrow (hybrid)',
    'Dark-eyed Junco x White-throated Sparrow (hybrid)',
    'Sagebrush Sparrow',
    "Bell's Sparrow",
    "Bell's Sparrow (belli)",
    "Bell's Sparrow (canescens)",
    "Bell's Sparrow (clementeae)",
    "Bell's Sparrow (cinerea)",
    'Vesper Sparrow',
    "Nelson's Sparrow",
    "Nelson's Sparrow (Interior)",
    'Savannah Sparrow',
    'Savannah Sparrow (Large-billed)',
    'Song Sparrow',
    'Song Sparrow (pusillula)',
    'Song Sparrow (rufina Group)',
    'Song Sparrow (heermanni Group)',
    'Song Sparrow (montana/merrilli)',
    "Lincoln's Sparrow",
    'Swamp Sparrow',
    "Abert's Towhee",
    'California Towhee',
    'Rufous-crowned Sparrow',
    'Green-tailed Towhee',
    'Spotted Towhee',
    'Yellow-breasted Chat',
    'Yellow-breasted Chat (virens)',
    'Yellow-headed Blackbird',
    'Bobolink',
    'Western Meadowlark',
    'Crested Oropendola',
    'Orchard Oriole',
    'Orchard Oriole (Orchard)',
    'Hooded Oriole',
    'Hooded Oriole (nelsoni Group)',
    'Epaulet Oriole',
    'Venezuelan Troupial',
    "Bullock's Oriole",
    'Baltimore Oriole',
    "Bullock's x Baltimore Oriole (hybrid)",
    "Scott's Oriole",
    'Yellow-breasted Chat x new world oriole sp. (hybrid)',
    'Red-winged Blackbird',
    'Red-winged Blackbird (Red-winged)',
    'Red-winged Blackbird (California Bicolored)',
    'Tricolored Blackbird',
    'Bronzed Cowbird',
    'Brown-headed Cowbird',
    'Rusty Blackbird',
    "Brewer's Blackbird",
    'Common Grackle',
    'Great-tailed Grackle',
    'Great-tailed Grackle (Western)',
    "Brewer's Blackbird x Great-tailed Grackle (hybrid)",
    'Ovenbird',
    'Worm-eating Warbler',
    'Northern Waterthrush',
    'Golden-winged x Blue-winged Warbler (hybrid)',
    'Black-and-white Warbler',
    'Prothonotary Warbler',
    'Tennessee Warbler',
    'Orange-crowned Warbler',
    'Orange-crowned Warbler (Gray-headed)',
    'Orange-crowned Warbler (orestera)',
    'Orange-crowned Warbler (lutescens)',
    'Orange-crowned Warbler (sordida)',
    'Orange-crowned Warbler (celata)',
    "Lucy's Warbler",
    'Nashville Warbler',
    'Nashville Warbler (ridgwayi)',
    "Virginia's Warbler",
    'Connecticut Warbler',
    "MacGillivray's Warbler",
    'Mourning Warbler',
    'Kentucky Warbler',
    'Common Yellowthroat',
    "MacGillivray's Warbler x Common Yellowthroat (hybrid)",
    'Hooded Warbler',
    'American Redstart',
    'Cape May Warbler',
    'Northern Parula',
    'Magnolia Warbler',
    'Bay-breasted Warbler',
    'Blackburnian Warbler',
    'Yellow Warbler',
    'Yellow Warbler (Northern)',
    'Common Yellowthroat x Yellow Warbler (hybrid)',
    'American Redstart x Yellow Warbler (hybrid)',
    'Chestnut-sided Warbler',
    'Blackpoll Warbler',
    'Black-throated Blue Warbler',
    'Palm Warbler',
    'Palm Warbler (Western)',
    'Pine Warbler',
    'Yellow-rumped Warbler',
    'Yellow-rumped Warbler (Myrtle)',
    "Yellow-rumped Warbler (Audubon's)",
    "Yellow-rumped Warbler (Myrtle x Audubon's)",
    'Cape May x Yellow-rumped Warbler (hybrid)',
    'Yellow-throated Warbler',
    'Prairie Warbler',
    "Grace's Warbler",
    "Yellow-rumped x Grace's Warbler (hybrid)",
    'Black-throated Gray Warbler',
    'Yellow-rumped x Black-throated Gray Warbler (hybrid)',
    "Townsend's Warbler",
    "Yellow-rumped x Townsend's Warbler (hybrid)",
    "Black-throated Gray x Townsend's Warbler (hybrid)",
    'Hermit Warbler',
    "Townsend's x Hermit Warbler (hybrid)",
    'Black-throated Gray x Hermit Warbler (hybrid)',
    'Black-throated Green Warbler',
    "Townsend's x Black-throated Green Warbler (hybrid)",
    'Canada Warbler',
    "Wilson's Warbler",
    "Wilson's Warbler (chryseola)",
    "Wilson's Warbler (pileolata)",
    'Painted Redstart',
    'Hepatic Tanager',
    'Summer Tanager',
    'Scarlet Tanager',
    'Western Tanager',
    'Northern Cardinal',
    'Yellow Grosbeak',
    'Rose-breasted Grosbeak',
    'Black-headed Grosbeak',
    'Rose-breasted x Black-headed Grosbeak (hybrid)',
    'Blue Grosbeak',
    'Lazuli Bunting',
    'Indigo Bunting',
    'Lazuli x Indigo Bunting (hybrid)',
    'Orange-breasted Bunting',
    'Painted Bunting',
    'Dickcissel',
    'Red-crested Cardinal',
    'Yellow-billed Cardinal',
    'White-lined Tanager',
    'Blue-gray Tanager',
    'Blue Dacnis',
    'Saffron Finch',
    'Grassland Yellow-Finch',
    'Blue-black Grassquit',
    'Parrot-billed Seedeater',
    'Cinnamon-rumped Seedeater',
    'Yellow-faced Grassquit',
];

async function seed() {
    const totalSteps = 6; // Total number of steps for the progress bar
    const progressBar = new SingleBar(
        {
            format: 'Seeding | {bar} | {percentage}% | {value}/{total}',
            barCompleteChar: '\u2588',
            barIncompleteChar: '\u2591',
            hideCursor: true,
        },
        Presets.shades_classic
    );

    progressBar.start(totalSteps, 0); // Start the progress bar

    await db.insert(states).values([{ id: 'US-CA', name: 'California' }]);
    progressBar.increment(); // Increment progress

    await db.insert(regions).values([
        { regionCode: 'US-CA-SDI', regionName: 'San Diego - Imperial' },
        { regionCode: 'US-CA-OR', regionName: 'Orange' },
        { regionCode: 'US-CA-LA', regionName: 'Los Angeles' },
        { regionCode: 'US-CA-IE', regionName: 'Inland Empire' },
        { regionCode: 'US-CA-SFB', regionName: 'San Francisco Bay' },
        { regionCode: 'US-CA-CC', regionName: 'Central Coast' },
        { regionCode: 'US-CA-NSJV', regionName: 'Northern San Joaquin Valley' },
        { regionCode: 'US-CA-SSJV', regionName: 'Southern San Joaquin Valley' },
        { regionCode: 'US-CA-SC', regionName: 'Superior California' },
        { regionCode: 'US-CA-NC', regionName: 'North Coast' },
    ]);
    progressBar.increment(); // Increment progress

    await db.insert(counties).values(
        Object.keys(countyRegionMapping).map((county) => ({
            countyName: county,
            stateCode: 'US-CA',
        }))
    );
    progressBar.increment(); // Increment progress

    await db.insert(countyRegions).values(
        Object.entries(countyRegionMapping).map(([county, region]) => ({
            countyName: county,
            stateCode: 'US-CA',
            regionCode: region,
        }))
    );
    progressBar.increment(); // Increment progress

    await db.insert(channelSubscriptions).values(
        Object.entries(regionChannels).map(([region, channels]) => ({
            regionCode: region,
            channelId: channels[0],
        }))
    );
    progressBar.increment(); // Increment progress

    await db
        .insert(channelSubscriptions)
        .values([{ stateId: 'US-CA', channelId: '1151958598264574002' }]);

    await db.insert(filteredSpecies).values(
        californiaFilter.map((species) => ({
            speciesCode: species,
            stateId: 'US-CA',
        }))
    );

    progressBar.increment(); // Increment progress

    progressBar.stop(); // Stop the progress bar
    console.log('Seeding completed!');
}

seed().catch((error) => {
    console.error('Seeding failed:', error);
});
