export interface eBirdObservation {
    comName: string;
    sciName: string;
    speciesCode: string;
    locId: string;
    locName: string;
    lat: number;
    lng: number;
    obsDt: number;
    howMany: number;
    obsValid: boolean;
    obsReviewed: boolean;
    locationPrivate: boolean;
    subId: string;
    countryCode: string;
    countryName: string;
    subnational1Code: string;
    subnational1Name: string;
    subnational2Code: string;
    subnational2Name: string;
    firstName: string;
    lastName: string;
    userDisplayName: string;
    obsId: string;
    checklistId: string;
    presenceNoted: boolean;
    hasRichMedia: boolean;
    hasComments: boolean;
    evidence: 'P' | 'A' | 'V' | null;
}
