name: CI
on:
  push: 
    branches: [ main ]
    paths: ['discord/**']
jobs:
  deploy:
    runs-on: self-hosted
    environment: Production
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "20.x"
      - name: Create .env
        working-directory: discord
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Stop current instance, install, and restart
        working-directory: discord
        run: |
          # Stop the current instance (if running)
          pm2 stop scrub-jay-discord || true
          npm install
          pm2 start index.js --name scrub-jay-discord
