name: CI
on:
  push: 
    branches: [ main ]
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "20.x"
      - name: Create .env
        working-directory: discord
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Install dependencies
        working-directory: discord
        run: npm install
      - name: Run index.js
        working-directory: discord
        run: pm2 start index.js
